# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.3'

target 'Vediohead' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks. React Native currently does not support use_frameworks!
  # use_frameworks!

  pod 'Firebase'
  pod 'Firebase/Core', '~> 4.13.0'
  # pod 'Firebase/AdMob', '~> 4.13.0'
  pod 'Firebase/Analytics', '~> 4.13.0'
  pod 'Firebase/Auth', '~> 4.13.0'
  # FirebaseCrash has been deprecated in favor of Crashlytics
  # pod 'Firebase/Crash', '~> 4.13.0'
  pod 'Firebase/Database', '~> 4.13.0'
  pod 'Firebase/DynamicLinks', '~> 4.13.0'
  pod 'Firebase/Messaging', '~> 4.13.0'
  # pod 'Firebase/Performance', '~> 4.13.0'
  pod 'Firebase/RemoteConfig', '~> 4.13.0'
  pod 'Firebase/Storage', '~> 4.13.0'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SentryReactNative', path: '../node_modules/react-native-sentry'

  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
  pod 'DoubleConversion', podspec: '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', podspec: '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  # For React Native >=0.54, use glog instead of GLog
  # pod 'glog', podspec: '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', podspec: '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'React', path: '../node_modules/react-native', subspecs: [
    'Core',
    'ART',
    'BatchedBridge',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTGeolocation',
    'RCTImage',
    'RCTPushNotification',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
  pod 'GoogleMaps'
  pod 'GoogleSignIn'
  pod 'CodePush', path: '../node_modules/react-native-code-push'
  pod 'RNAudio', path: '../node_modules/react-native-audio/RNAudio.podspec'
  pod 'RNSound', path: '../node_modules/react-native-sound'
  pod 'RNFirebase', path: '../node_modules/react-native-firebase/ios'
  pod 'RNGestureHandler', path: '../node_modules/react-native-gesture-handler/ios'
  pod 'RNThumbnail', path: '../node_modules/react-native-thumbnail'
  pod 'RNVectorIcons', path: '../node_modules/react-native-vector-icons'
  pod 'react-native-autogrow-textinput', path: '../node_modules/react-native-autogrow-textinput'
  pod 'react-native-camera', path: '../node_modules/react-native-camera'
  pod 'react-native-fbsdk', path: '../node_modules/react-native-fbsdk/ios'
  pod 'react-native-fetch-blob', path: '../node_modules/react-native-fetch-blob'
  pod 'react-native-image-picker', path: '../node_modules/react-native-image-picker'
  pod 'react-native-splash-screen', path: '../node_modules/react-native-splash-screen'
  pod 'react-native-video', path: '../node_modules/react-native-video'
  pod 'react-native-maps', path: '../node_modules/react-native-maps'
  pod 'react-native-fcm', path: '../node_modules/react-native-fcm'
  pod 'react-native-google-maps', path: '../node_modules/react-native-maps'
  pod 'react-native-gps-state', path: '../node_modules/react-native-gps-state'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['DYLIB_COMPATIBILITY_VERSION'] = ''
    end
  end
end
