export const InfoHubData = [
  {
    key: '1',
    submittedBy: '@chris',
    submittedAt: '10 mins ago',
    thumbnailUrl: 'https://viaplaceholder.com/1080x1920.png/09f/fff',
    type: 'weather',
    infoBorderColor: 'blue',
  },
  {
    key: '2',
    submittedBy: '@shelby',
    submittedAt: '10 mins ago',
    thumbnailUrl: 'https://viaplaceholder.com/1080x1920.png/56a/fff',
    type: 'law and order',
    infoBorderColor: 'red',
  },
  {
    key: '3',
    submittedBy: '@patrick',
    submittedAt: '10 mins ago',
    thumbnailUrl: 'https://viaplaceholder.com/1080x1920.png/22b/fff',
    type: 'general',
    infoBorderColor: 'orange',
  },
  {
    key: '4',
    submittedBy: '@penelope',
    submittedAt: '10 mins ago',
    thumbnailUrl: 'https://viaplaceholder.com/1080x1920.png/c4f/fff',
    type: 'events',
    infoBorderColor: 'magenta',
  },
  {
    key: '5',
    submittedBy: '@nicole',
    submittedAt: '10 mins ago',
    thumbnailUrl: 'https://viaplaceholder.com/1080x1920.png/04d/fff',
    type: 'traffic',
    infoBorderColor: 'green',
  },
  {
    key: '6',
    submittedBy: '@mary',
    submittedAt: '10 mins ago',
    thumbnailUrl: 'https://viaplaceholder.com/1080x1920.png/88d/fff',
    type: 'newsworthy',
    infoBorderColor: 'purple',
  },
  {
    key: '7',
    submittedBy: '@penelope',
    submittedAt: '10 mins ago',
    thumbnailUrl: 'https://viaplaceholder.com/1080x1920.png/aa3/fff',
    type: 'newsworthy',
    infoBorderColor: 'purple',
  },
  {
    key: '8',
    submittedBy: '@nicole',
    submittedAt: '10 mins ago',
    thumbnailUrl: 'https://viaplaceholder.com/1080x1920.png/0bb/fff',
    type: 'law and order',
    infoBorderColor: 'red',
  },
  {
    key: '9',
    submittedBy: '@mary',
    submittedAt: '10 mins ago',
    thumbnailUrl: 'https://viaplaceholder.com/1080x1920.png/033/fff',
    type: 'events',
    infoBorderColor: 'magenta',
  },
];
