export const BountyVerificationData = [
  {
    key: '1',
    bounty: '9',
    submittedBy: '@chris',
    submittedAt: '10 mins ago',
    type: 'infoHubEntry',
    verifiedCounts: '2',
    notVerifiedCounts: '0',
    surveyCompany: '',
    surveySize: '',
    surveyDuration: '',
  },
  {
    key: '2',
    bounty: '9',
    submittedBy: '@nicole',
    submittedAt: '10 mins ago',
    type: 'barcodeEntry',
    verifiedCounts: '2',
    notVerifiedCounts: '0',
    surveyCompany: '',
    surveySize: '',
    surveyDuration: '',
  },
  {
    key: '3',
    bounty: '10',
    submittedBy: '',
    submittedAt: '',
    type: 'surveyEntry',
    verifiedCounts: '',
    notVerifiedCounts: '',
    surveyCompany: 'ABCD',
    surveySize: '40',
    surveyDuration: '40',
  },
  {
    key: '4',
    bounty: '3',
    submittedBy: '@shelby',
    submittedAt: '10 mins ago',
    type: 'infoHubEntry',
    verifiedCounts: '0',
    notVerifiedCounts: '2',
    surveyCompany: '',
    surveySize: '',
    surveyDuration: '',
  },
  {
    key: '5',
    bounty: '9',
    submittedBy: '@luke',
    submittedAt: '10 mins ago',
    type: 'barcodeEntry',
    verifiedCounts: '2',
    notVerifiedCounts: '1',
    surveyCompany: '',
    surveySize: '',
    surveyDuration: '',
  },
  {
    key: '6',
    bounty: '9',
    submittedBy: '@patsy',
    submittedAt: '10 mins ago',
    type: 'barcodeEntry',
    verifiedCounts: '2',
    notVerifiedCounts: '0',
    surveyCompany: '',
    surveySize: '',
    surveyDuration: '',
  },
  {
    key: '7',
    bounty: '3',
    submittedBy: '@john',
    submittedAt: '10 mins ago',
    type: 'infoHubEntry',
    verifiedCounts: '0',
    notVerifiedCounts: '2',
    surveyCompany: '',
    surveySize: '',
    surveyDuration: '',
  },
  {
    key: '8',
    bounty: '3',
    submittedBy: '@john',
    submittedAt: '10 mins ago',
    type: 'infoHubEntry',
    verifiedCounts: '1',
    notVerifiedCounts: '0',
    surveyCompany: '',
    surveySize: '',
    surveyDuration: '',
  },
  {
    key: '9',
    bounty: '6',
    submittedBy: '@alex',
    submittedAt: '10 mins ago',
    type: 'barcodeEntry',
    verifiedCounts: '0',
    notVerifiedCounts: '1',
    surveyCompany: '',
    surveySize: '',
    surveyDuration: '',
  },
  {
    key: '10',
    bounty: '3',
    submittedBy: '@mark',
    submittedAt: '10 mins ago',
    type: 'barcodeEntry',
    verifiedCounts: '1',
    notVerifiedCounts: '2',
    surveyCompany: '',
    surveySize: '',
    surveyDuration: '',
  },
  {
    key: '11',
    bounty: '6',
    submittedBy: '@raj',
    submittedAt: '10 mins ago',
    type: 'barcodeEntry',
    verifiedCounts: '0',
    notVerifiedCounts: '2',
    surveyCompany: '',
    surveySize: '',
    surveyDuration: '',
  },
  {
    key: '12',
    bounty: '15',
    submittedBy: '',
    submittedAt: '',
    type: 'surveyEntry',
    verifiedCounts: '',
    notVerifiedCounts: '',
    surveyCompany: 'ABCD',
    surveySize: '60',
    surveyDuration: '30',
  },
  {
    key: '13',
    bounty: '3',
    submittedBy: '@alice',
    submittedAt: '10 mins ago',
    type: 'infoHubEntry',
    verifiedCounts: '2',
    notVerifiedCounts: '0',
    surveyCompany: '',
    surveySize: '',
    surveyDuration: '',
  },
  {
    key: '14',
    bounty: '3',
    submittedBy: '@wesley',
    submittedAt: '10 mins ago',
    type: 'infoHubEntry',
    verifiedCounts: '2',
    notVerifiedCounts: '0',
    surveyCompany: '',
    surveySize: '',
    surveyDuration: '',
  },
  {
    key: '15',
    bounty: '30',
    submittedBy: '',
    submittedAt: '',
    type: 'surveyEntry',
    verifiedCounts: '',
    notVerifiedCounts: '',
    surveyCompany: 'ABCD',
    surveySize: '100',
    surveyDuration: '45',
  },
  {
    key: '16',
    bounty: '6',
    submittedBy: '@paul',
    submittedAt: '10 mins ago',
    type: 'barcodeEntry',
    verifiedCounts: '1',
    notVerifiedCounts: '1',
    surveyCompany: '',
    surveySize: '',
    surveyDuration: '',
  },
  {
    key: '17',
    bounty: '3',
    submittedBy: '@tiara',
    submittedAt: '10 mins ago',
    type: 'infoHubEntry',
    verifiedCounts: '1',
    notVerifiedCounts: '1',
    surveyCompany: '',
    surveySize: '',
    surveyDuration: '',
  },
  {
    key: '18',
    bounty: '3',
    submittedBy: '@adria',
    submittedAt: '10 mins ago',
    type: 'infoHubEntry',
    verifiedCounts: '0',
    notVerifiedCounts: '2',
    surveyCompany: '',
    surveySize: '',
    surveyDuration: '',
  },
  {
    key: '19',
    bounty: '3',
    submittedBy: '@nicole',
    submittedAt: '10 mins ago',
    type: 'barcodeEntry',
    verifiedCounts: '1',
    notVerifiedCounts: '0',
    surveyCompany: '',
    surveySize: '',
    surveyDuration: '',
  },
];
